# Filebeat config for Cowrie Honeypot
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /home/cowrie/cowrie/var/log/cowrie/cowrie.json
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      sensor: cowrie

output.elasticsearch:
  enabled: false

output.logstash:
  enabled: true
  hosts: ["localhost:5044"]

# Optional: Logging
logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
    permissions: 0644
